// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYlfcgfGAYPuso2YvvWjBoxBvG7f04kgg',
    appId: '1:1028398753139:android:d1690193e0a292b923d106',
    messagingSenderId: '1028398753139',
    projectId: 'jarmpnj',
    storageBucket: 'jarmpnj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgTGy0v-P3762TzBgunqzkRVyeDRo4Ug4',
    appId: '1:1028398753139:ios:f5c169f2fc6901d423d106',
    messagingSenderId: '1028398753139',
    projectId: 'jarmpnj',
    storageBucket: 'jarmpnj.appspot.com',
    androidClientId: '1028398753139-klv7n57461d4ktjublmn4eo024catb35.apps.googleusercontent.com',
    iosClientId: '1028398753139-rpsrsoe9t7h88l2oocj5ui1s0253vdhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarmpnj',
  );
}
